apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: dev
  labels:
   app: utrains
spec:
  containers:
    - name: kaka-app
      image: httpd
#      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP